# Generated by Django 3.2.3 on 2022-04-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFA145', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ont', 'On track'), ('ar', 'At risk'), ('oft', 'Off track'), ('oh', 'On hold'), ('c', 'Complete')], max_length=20, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=999)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('member', models.ManyToManyField(related_name='workbox_member', to='pm.P')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workbox',
                'verbose_name_plural': 'Workboxes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('completed', models.BooleanField(default=False, verbose_name='Завершена?')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Конец Дата')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Конец Время')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('priority', models.CharField(blank=True, choices=[('l', 'Низкий'), ('m', 'Средний'), ('h', 'Высокий'), ('n', 'Нет Приоритета')], max_length=10, null=True, verbose_name='Важность')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.p', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='p',
            name='workbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.w'),
        ),
    ]
